#### configuration

VERSION        = 3.17.0
NAME           = palevim
UUID           = vimperator@mozdev.org
MIN_VERSION    = 28.0
MAX_VERSION    = 28.*

-include private.properties

include ../common/Makefile
